### ISSUE TITLE
islandora_object_load() not loading book object in islandora_bagit_complex.module

### ISSUE THREAD

**Issue by tomboone** [mjordan/islandora_bagit_complex#4]
After enabling islandora_bagit_complex and checking 'Books' under 'Complex objects' at /admin/islandora/tools/bagit, when I attempt to bag a book and its pages via drush (e.g., `drush --user=1 create-islandora-bag object grant:595`), while the book object is bagged, none of the pages are bagged.

Specifically, the following error message is generated:
`in_array() expects parameter 2 to be array, null given            [warning]
islandora_bagit_complex.module:30`

Meaning that $parent_object_models is null.

Via debugging, I've also confirmed that $parent_object in line 13 is also null, though $pid is properly populated with the book objects PID (e.g., grant:595). This would seem to mean that islandora_object_load($pid) is not actually loading the book object, resulting in all derivative object values also being null.

When executing the module code manually using /devel/php (and manually defining $pid), everything works properly (albeit timing out, as would be expected), including islandora_object_load(). But for whatever reason it doesn't work for me in the islandora_bagit_complex module's hook_islandora_bagit_post_create() function.

### Stack Info
OS: 18.04.5 LTS (Bionic Beaver)
PHP: 7.2.24-0ubuntu0.18.04.6
Database: 5.5.5-10.1.44-MariaDB-0ubuntu0.18.04.1
Web Server: Apache/2.4.29 (Ubuntu) 

Drupal: 7.73
Islandora: 7.x-dev
Islandora BagIt: 7.x-dev
Islandora BagIt Complex: 7.x-dev

Islandora complex book object used in testing: https://islandora.wrlc.org/islandora/object/grant%3A595

**Comment by mjordan** [comment]
I'll investigate.

@bondjimbond you ever seen this behavior?

**Comment by bondjimbond** [comment]
Nope, it's new to me. I do use the Books setting, so you'd think I'd hit this problem, but I've never seen it before.

**Comment by mjordan** [comment]
OK thanks. @tomboone  I'll try to replicate or at least figure where we could be checking for null parent object. If I push a fix branch, are you in a position to test it?

**Comment by tomboone** [comment]
Absolutely. Thanks, @mjordan. Let me know if you need any more info.

**Comment by tomboone** [comment]
@mjordan Our installation is a multi-tenant one set up by DGI that predates my arrival at WRLC. I don't know if that would play a role in creating this bug or not, but I figured it best to mention it before you invest too much time.

In this setup, any object included in any tenant site will also be included in the "umbrella" islandora.wrlc.org site. Because of this, the object I linked to above lives at both:
https://islandora.wrlc.org/islandora/object/grant%3A595
https://dcislandora.wrlc.org/islandora/object/grant%3A595

...though it has the same PID on both sites.

The islandora_bagit module doesn't appear to utilize the --uri drush flag, so I've been running all drush commands without it, which defaults to islandora.wrlc.org and is working just fine to bag non-complex objects/collections.

Creating bag of that sample object in the UI at both islandora.wrlc.org and dcislandora.wrlc.org generates the same in_array() parameter error in Watchdog as does running the drush command.

As I said, this may have no bearing on why the error is occurring, but figured I should add that info in case it does.

**Comment by mjordan** [comment]
I think your environment is the same as @bondjimbond's, but he can correct me.

**Comment by bondjimbond** [comment]
Yes, the setup (and vendor) is the same as mine.

**Comment by mjordan** [comment]
@tomboone Any chance there's a XACML policy on the book that is failing?

**Comment by tomboone** [comment]
@mjordan Doesn't look like it:

![image](https://user-images.githubusercontent.com/20044572/95497917-139ddf80-0971-11eb-819e-8a357ad9b25c.png)

**Comment by tomboone** [comment]
@mjordan This might be a more useful screenshot to address your XACML question (regarding the entire repo):

![Screen_Shot_2020-10-15_at_2_17_39_PM](https://user-images.githubusercontent.com/20044572/96170593-caf6a100-0ef1-11eb-9bd3-858fa6a244d0.png)

**Comment by tomboone** [comment]
@mjordan This might provide more relevant info than my previous screenshot, regarding the XACML policies on the entire repo:

![Screen_Shot_2020-10-15_at_2_17_39_PM](https://user-images.githubusercontent.com/20044572/96170795-0ee9a600-0ef2-11eb-86c5-2d43172c47ef.png)

That said, I don't know how/where to check to see if a policy is failing.

**Comment by mjordan** [comment]
@tomboone sorry to drop this. I know your sites are live, but is there any chance you can add some debugging code in the islandora.module's `islandora_object_load()` function (line 1240) to see why it's returning `NULL`? Maybe using `dd()` if you have the devel module enabled.

**Comment by tomboone** [comment]
@mjordan I used `dd()` to test bagging of this book object:
https://auislandora-stage.wrlc.org/islandora/object/auislandora:35639

I debugged $parent_object_models first, but it wrote an empty line to the log. Same result for $parent_object. (This confirmed what I already knew about them both being `null`) So I debugged $pid, and it logged its value as `auislandora_35639`.

So something is replacing the colon with an underscore BEFORE it hits this module's function, perhaps somewhere in islandora_bagit—or somewhere specific to our environment. I'll do some more debugging and see if I can determine where that substitution is happening.

**Comment by mjordan** [comment]
That happens at https://github.com/Islandora/islandora_bagit/blob/7.x/islandora_bagit.module#L334 (for example) but what's strange is that it's only happening for you. I can't replicate it, and @bondjimbond hasn't experienced it (that I know of). See where else it is happening (^^ might be the only place, but that PID with the `_` is used in the Bag filename) and we can go from there.

**Comment by mjordan** [comment]
@tomboone did you resolve this? Anything I can do?

**Comment by tomboone** [comment]
@mjordan I haven't had a chance to get back to it. We've discussed forking islandora_bagit to use a separate variable for setting the Bag filename so the $pid fed to this module is guaranteed to be unaltered (and then submit a pull request for you to look at), but I haven't had time to work on that idea. I also haven't had a chance to test whether the altered $pid is showing up elsewhere. I'm hoping to make some progress by the end of January.
